source "https://rubygems.org"

require "yaml"
require "securerandom"
require "digest/sha1"
gem "rack"
gem "tilt"
gem "sinatra", :require => "sinatra/base"
gem "sequel"
gem "sqlite3"
gem "slim"
gem "bcrypt"
gem "trueskill-ranked", :require => "TrueSkill"
gem "tassadar"
